### ISSUE TITLE
Rest API return duplicated products

### ISSUE THREAD

**Issue by PterodactylStore** [OnTheGoSystems/edd-multilingual#16]
Steps to reproduce the behavior
1)i nstall EDD WPML addon
2) go to /en/edd-api/v2/products or /{lang}/edd-api/v2/products
3) you get duplicated products for all langauges

Information (if a specific version is affected):
PHP Version:
8.1

EDD Version (or branch):
last
WordPress Version:
last
Any other relevant information:

should return only products for active language in the url api

**Comment by dgwatkins** [comment]
Thanks for the report.

I have confirmed the issue and started looking into a solution.

Unfortunately, Easy Digital Downloads doesn't expose a hook I can use to fix this. I will be contacting the author to explore the possibility of adding one for us to use here.

Meanwhile, as a temporary workaround, you can edit `includes/api/class-edd-api-v2.php` line 43 and change the value of `suppress_filters` from `true` to `false`:

```
diff --git a/includes/api/class-edd-api-v2.php b/includes/api/class-edd-api-v2.php
index b3c2d31..fc12813 100644
--- a/includes/api/class-edd-api-v2.php
+++ b/includes/api/class-edd-api-v2.php
@@ -40,7 +40,7 @@ class EDD_API_V2 extends EDD_API_V1 {
                        $query_args = array(
                                'post_type'        => 'download',
                                'posts_per_page'   => $this->per_page(),
-                               'suppress_filters' => true,
+                               'suppress_filters' => false,
                                'paged'            => $this->get_paged(),
                                'order'            => $args['order'],
                                'orderby'          => $args['orderby'],
```

I will keep this ticket updated with any progress.

**Comment by PterodactylStore** [comment]
thank you i try this and is work

**Comment by PterodactylStore** [comment]
![image](https://github.com/OnTheGoSystems/edd-multilingual/assets/133764150/03353673-a2c5-435a-a0e6-2553d5e608be)

also im just noticed that when enable featured product is duplicated and sales and reviews not synced

**Comment by dgwatkins** [comment]
Hi @PterodactylStore 

Easy Digital Downloads author has added a hook in 3.2.2 that we can use.

Remember to re-apply the workaround above if you update the plugin on your site.

Meanwhile, we will use the hook to resolve this issue and release version 1.4.1 shortly.

When we release, you wont have to apply the workaround any longer.

Thanks for the report!
