### ISSUE TITLE
duplicate download tags and categories in sitemap

### ISSUE THREAD

**Issue by PterodactylStore** [OnTheGoSystems/edd-multilingual#17]
![tag](https://github.com/OnTheGoSystems/edd-multilingual/assets/133764150/03906b08-45ec-4234-be3b-35da0a6565de)
![cat](https://github.com/OnTheGoSystems/edd-multilingual/assets/133764150/b63fab68-60c8-426e-9176-b333966d52e5)

other post type is works good but download tags and categories is duplicated for all languages see the screenshots

**Comment by dgwatkins** [comment]
Thanks for the report @PterodactylStore 

I am afraid this might not be related to Easy Digital Downloads, but to Rank Math SEO instead.

Can you confirm that you are using our "WPML SEO" plugin? This is the sort of problem that "WPML SEO" resolves.

The requirements are described in our site here:
https://wpml.org/plugin/rank-math-seo/#:~:text=This%20plugin%20requires%20the%20WPML%20SEO%20glue%20plugin%20for%20full%20compatibility.

... and in RankMath's site over here:
https://rankmath.com/kb/multilingual-seo-wpml/#getting-started

**Comment by PterodactylStore** [comment]
yes i have already WPML SEO plugin

other sitemaps are working good
only downloads tags and categories pages that have duplicated in sitemaps url for lamgauges 
![image](https://github.com/OnTheGoSystems/edd-multilingual/assets/133764150/b56755a0-0430-44cd-aee9-4b1d5fca693f)

**Comment by PterodactylStore** [comment]
also see my other bug report
about products reviews not synced betwen other languages

**Comment by strategio** [comment]
Hi @PterodactylStore,

Can I kindly ask you to contact the WPML support on https://wpml.org/forums/forum/english-support/ (chat or ticket)?
There we have more tools to assist you and maybe provide a temporary solution.
You can refer to this Github issue in your WPML ticket.

Thanks,
Pierre

**Comment by dgwatkins** [comment]
As far as I can see, this is all correct:
- Sitemaps are only divided per language when the URL format in WPML is configured to be "one domain per language". Otherwise the sitemap contains all languages together.

Please open a support request at wpml.org if you keep having issues (as Pierre mentioned above).

Closing here for now.
