### ISSUE TITLE
Fatal error when using wpml:master with edd-multilingual:master

### ISSUE THREAD

**Issue by dimitrismitsis** [OnTheGoSystems/edd-multilingual#6]
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function WPML_WPDB_And_SP_User::__construct(), 1 passed in edd-multilingual/class-edd-multilingual.php on line 72 and exactly 2 expected in sitepress-multilingual-cms/classes/core-abstract-classes/class-wpml-wpdb-and-sp-user.php on line 15`

https://github.com/OnTheGoSystems/edd-multilingual/pull/5#issuecomment-360879811

**Comment by dgwatkins** [comment]
@dimitrismitsis This is fixed with WPML 4.0
